<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.2">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week 12: Discover the Perfect Spell! – Bayesian Statistical Methods in Medicine &amp; Health</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./M06_1.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-07c16812f08c4a1591d6ec4fc46327fa.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8da5b4427184b79ecddefad3d342027e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<script src="site_libs/viz-1.8.2/viz.js"></script>

<link href="site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">

<script src="site_libs/grViz-binding-1.0.11/grViz.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./M06_2.html">Week 12: <strong>Discover the Perfect Spell!</strong></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bayesian Statistical Methods in Medicine &amp; Health</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Preface</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Introduction</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./installation_guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Software Installation Guide</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./brief_module_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Module 1:</strong> Bayesian Dreams!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M01_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1: <strong>Navigating Evidence</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M01_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2: <strong>Bayesian Inference</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./brief_module_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Module 2:</strong> Chaotics?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M02_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3: <strong>Prior and Posterior</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M02_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4: <strong>Generative Models and Tools</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./brief_module_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Module 3:</strong> Bayeswatch - Gaussian!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M03_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5: <strong>Logical Connections</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M03_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6: <strong>Prior Tweaks and More</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./brief_module_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Module 4:</strong> Bayeswatch - Non Gaussian!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M04_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7: <strong>Non-Gaussian</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M04_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 8: <strong>More on Non-Gaussian</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./brief_module_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Module 5:</strong> Clusterphobia?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M05_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 9: <strong>Cluster Smart with Bayes</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M05_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 10: <strong>Goldilocks</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./brief_module_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>Module 6:</strong> Wander into the Wonder!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M06_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 11: <strong>Size Matters!</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M06_2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Week 12: <strong>Discover the Perfect Spell!</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learnings" id="toc-learnings" class="nav-link active" data-scroll-target="#learnings">Learnings</a></li>
  <li><a href="#adaptivity" id="toc-adaptivity" class="nav-link" data-scroll-target="#adaptivity">Adaptivity</a>
  <ul class="collapse">
  <li><a href="#antibiotic-safety-trial" id="toc-antibiotic-safety-trial" class="nav-link" data-scroll-target="#antibiotic-safety-trial">Antibiotic Safety Trial</a></li>
  <li><a href="#interim-analyses" id="toc-interim-analyses" class="nav-link" data-scroll-target="#interim-analyses">Interim Analyses</a></li>
  </ul></li>
  <li><a href="#bayesian-model-choice" id="toc-bayesian-model-choice" class="nav-link" data-scroll-target="#bayesian-model-choice">Bayesian Model Choice</a></li>
  <li><a href="#bayes-factor" id="toc-bayes-factor" class="nav-link" data-scroll-target="#bayes-factor">Bayes Factor</a>
  <ul class="collapse">
  <li><a href="#probabilistic-view-point" id="toc-probabilistic-view-point" class="nav-link" data-scroll-target="#probabilistic-view-point">Probabilistic View Point</a></li>
  <li><a href="#bf-for-bayesian-models" id="toc-bf-for-bayesian-models" class="nav-link" data-scroll-target="#bf-for-bayesian-models">BF for Bayesian Models</a></li>
  <li><a href="#example-in-practice" id="toc-example-in-practice" class="nav-link" data-scroll-target="#example-in-practice">Example in Practice</a></li>
  </ul></li>
  <li><a href="#information-criteria" id="toc-information-criteria" class="nav-link" data-scroll-target="#information-criteria">Information Criteria</a>
  <ul class="collapse">
  <li><a href="#dic" id="toc-dic" class="nav-link" data-scroll-target="#dic">DIC</a></li>
  <li><a href="#waic" id="toc-waic" class="nav-link" data-scroll-target="#waic">WAIC</a></li>
  <li><a href="#loo" id="toc-loo" class="nav-link" data-scroll-target="#loo">LOO</a></li>
  <li><a href="#example-in-practice-1" id="toc-example-in-practice-1" class="nav-link" data-scroll-target="#example-in-practice-1">Example in Practice</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#live-tutorial-and-discussion" id="toc-live-tutorial-and-discussion" class="nav-link" data-scroll-target="#live-tutorial-and-discussion">Live tutorial and discussion</a></li>
  <li><a href="#tutorial-exercises" id="toc-tutorial-exercises" class="nav-link" data-scroll-target="#tutorial-exercises">Tutorial Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 12: <strong>Discover the Perfect Spell!</strong></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>NOT READY YET</p>
<iframe width="500" height="300" src="https://www.youtube.com/embed/VIDEO_ID" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<section id="learnings" class="level2">
<h2 class="anchored" data-anchor-id="learnings">Learnings</h2>
<ul>
<li><strong>Outcomes</strong></li>
</ul>
<p>– LO4: Demonstrate proficiency in using statistical software packages (R) to specify and fit models, assess model fit, detect and remediate non-convergence, and compare models.</p>
<p>– LO5: Engage in specifying, checking and interpreting Bayesian statistical analyses in practical problems using effective communication with health and medical investigators.</p>
<ul>
<li><strong>Objectives</strong></li>
</ul>
<p>By the end of this week you should be able to:</p>
<p>…</p>
</section>
<section id="adaptivity" class="level2">
<h2 class="anchored" data-anchor-id="adaptivity">Adaptivity</h2>
<iframe width="500" height="300" src="https://www.youtube.com/embed/VIDEO_ID" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p>In this course, we will introduce the fundamental conpects of Bayesian adaptive design. For interested readers to learn more, we refer to the book by <span class="citation" data-cites="berry2010bayesian">Berry et al. (<a href="references.html#ref-berry2010bayesian" role="doc-biblioref">2010</a>)</span>.</p>
<p>Adaptive designs are an increasingly popular approach in clinical trials, offering flexibility to modify trial procedures based on accumulating data without undermining the study’s integrity or validity. One powerful framework for implementing adaptive designs is through Bayesian methods.</p>
<div class="cell">
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-d2c107a4c5cfd2763ee2" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-d2c107a4c5cfd2763ee2">{"x":{"diagram":"\ndigraph seamless_design {\n  graph [layout = dot, rankdir = TB]\n\n  node [shape = box, style = filled, color = lightblue]\n  start [label = \"Initiate Data Collection\n(Initial Allocation and Sampling Rules)\"]\n  analyze [label = \"Analyse Available Data\"]\n  decision [label = \"Stopping Rule Met?\", shape = diamond, style = filled, color = green]\n  continue [label = \"Continue Data Collection\n(Revise Allocation and Sampling Rules)\"]\n  stop [label = \"Stop Trial or Go to the Next Phase\"]\n\n  start -> analyze\n  analyze -> decision\n  decision -> continue [label = \"No\"]\n  decision -> stop [label = \"Yes\"]\n  continue -> analyze\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Adaptive trials are designed with flexibility built in from the start. This means we can pre-plan adjustments to key elements like treatment types (dose, frequency, combinations), how patients are assigned to different treatments, which patient groups to include, and even how many participants are needed.</p>
<p>What makes this approach powerful is its ability to learn as it goes. As data rolls in, the trial can start to focus more on the treatment arms that are showing promise. That allows us to begin with a broader range of options, maybe testing 8 doses instead of just 3, and still use fewer participants overall.</p>
<p>A well-designed adaptive trial doesn’t just benefit researchers. Patients may get better treatments, regulators get more informative results, and the entire development process becomes more streamlined.</p>
<p>That said, the flip side is that adaptive designs take more effort to build. They require careful planning and trial simulations to make sure they perform well and stand up to regulatory standards. This means close collaboration of statisticians, clinicians, regulatory teams, operations, supply chain, and more all need to be in sync. When done right, though, the payoff is a trial design that’s not only smarter, but truly better for everyone involved.</p>
<!--

Unlike traditional fixed designs, Bayesian adaptive trials continuously update inferences about treatment safety or efficacy using Bayes’ theorem, enabling more responsive and efficient decision-making throughout the study.

A key advantage of Bayesian adaptive design is its ability to accumulate data, that reflect current evidence. The posterior probabilities are then used to make decisions, such as:

- Stopping early for success or futility
- Adjusting randomisation probabilities (e.g., favoring better-performing arms)
- Re-estimating sample sizes
- Dropping or adding treatment arms

Such flexibility leads to more efficient use of resources, shorter trial durations, and improved ethical standards by potentially exposing fewer participants to inferior treatments.

Bayesian adaptive designs are particularly well-suited for early-phase trials, rare diseases, or emerging fields where data may be limited but timely decision-making is essential. They also provide a transparent and interpretable framework for stakeholders by quantifying uncertainty and probability in a direct and intuitive way.



-->
<!--

### Frequentist vs. Bayesian Adaptive Design

Frequentist adaptive designs focus on controlling Type I error across potential changes, and typically treat adaptations conservatively. Whereas, Bayesian adaptive designs are more fluid and intuitive, allowing for seamless incorporation of prior knowledge and flexible decision rules based on evolving data.


| **Aspect** | **Frequentist Adaptive Design** | **Bayesian Adaptive Design** |
|------------|----------------------------------|-------------------------------|
| **Decision Criteria** | Uses pre-specified statistical thresholds (e.g., p-values, test statistics) | Uses posterior probabilities (e.g., Pr(efficacy > control) > 0.95) |
| **Adaptation Mechanism** | Adaptations are allowed but need strict pre-specification and complex error control (e.g., alpha spending) | Adaptations are based on real-time Bayesian updating and often easier to implement statistically |
| **Interim Analysis** | Typically limited in number and scope due to multiplicity concerns | Easily accommodates multiple or continuous interim looks without requiring multiplicity correction |
| **Interpretation of Results** | P-values and confidence intervals with long-run error control | Probabilistic statements about treatment effects (e.g., “there is a 95% chance the treatment is effective”) |
| **Complexity & Transparency** | Often requires extensive simulations to control Type I error across adaptations | Still requires simulation but often more intuitive and transparent in rationale |
| **Flexibility** | Adaptations must be rigidly pre-defined | More naturally allows flexibility and dynamic decision-making during the trial |



-->
<section id="antibiotic-safety-trial" class="level3">
<h3 class="anchored" data-anchor-id="antibiotic-safety-trial">Antibiotic Safety Trial</h3>
<p>Let’s expain the adaptivity and realted sample size calculation based on the antibiotic safety trila we discussed earlier, where we want to evaluate if a new antibiotic is safer than the standard treatment for bacterial pneumonia in children aged 6 months to 5 years.</p>
<p><strong>Design Features</strong></p>
<ul>
<li>Randomisation: 1:1 (New Antibiotic vs.&nbsp;Standard of Care)</li>
<li>Prior Beliefs: Non-informative priors for both arms (e.g., Beta(1,1) for safety rates)</li>
<li>Control Safety Rate: Estimated at 60%</li>
<li>Treatment Safety Rate: Estimated at 70% (say, about 10% point difference)</li>
<li>Planned Sample Size: Let’s assume 200 total (100 per group)</li>
<li>Interim Analyses: After 50, 100, and 150 participants have been followed</li>
</ul>
<p><strong>Decision Rule</strong></p>
<ul>
<li>If <span class="math inline">\(Pr(\theta_{trt} &gt; \theta_{crt}) &gt; 0.95\)</span> then consider early success</li>
<li>If <span class="math inline">\(Pr(\theta_{trt} &lt; \theta_{crt}) &gt; 0.95\)</span> then consider futility (stop for harm)</li>
<li>Else continue to next interim or if in the final interim then either it is inconclusive or conclude as no added benefit.</li>
</ul>
</section>
<section id="interim-analyses" class="level3">
<h3 class="anchored" data-anchor-id="interim-analyses">Interim Analyses</h3>
<p>At the first interim, conducted after enrolling 50 participants (25 in each group), suppose we observed that 17 children in the treatment group (i.e., <span class="math inline">\(\approx\)</span> 70%) and 15 in the control group experienced no adverse events (i.e., 60%). Starting with weakly-informative <span class="math inline">\(\text{Beta}(2,2)\)</span> priors, we updated the posterior distributions based on this data. For the treatment group, this yielded a <span class="math inline">\(\text{Beta}(19, 10)\)</span> distribution, and for the control group, a <span class="math inline">\(\text{Beta}(17, 12)\)</span>. We then calculated the posterior probability that the new antibiotic is safer than the standard treatment, especifically, <span class="math inline">\(Pr(\theta_{\text{trt}} &gt; \theta_{\text{crt}})\)</span> (which is 0.71, see R code and results below). According to our decision rules, if this probability exceeds 0.95, we would consider stopping the trial early for efficacy. Conversely, if the probability that the treatment is worse exceeds 0.95, we would stop for futility. Since neither condition was met (i.e., this probability is 0.71), we proceeded to the next interim analysis.</p>
<p>During the second interim analysis, conducted after 100 participants had been followed (50 per group), our cumulative data showed that 36 out of 50 participants in the treatment group and 29 out of 50 in the control group had no adverse events. We updated the posterior distributions accordingly: <span class="math inline">\(\text{Beta}(38, 16)\)</span> for the treatment group and <span class="math inline">\(\text{Beta}(31, 23)\)</span> for the control group. Once again, we computed the posterior probability of treatment superiority (which is as 0.93 in our case, see R code and results below). If this probability had exceeded our predefined threshold (greater than 0.95), we would have stopped the trial early for success. Since the threshold was not reached (i.e., this probability is 0.93), we decided to continue to the final planned interim.</p>
<p>The <strong>third interim analysis</strong> took place after 150 participants had been enrolled and followed (75 per group). At this point, 57 participants in the treatment arm and 45 in the control arm experienced no adverse events. These data produced updated posterior distributions: <span class="math inline">\(\text{Beta}(59, 20)\)</span> for the treatment and <span class="math inline">\(\text{Beta}(47, 32)\)</span> for the control. We calculated the final posterior probability that the treatment is safer than the control (which is 0.98, see R code and results below). If the final probability exceeded 0.95, we planned to declare the trial a success and conclude that the new antibiotic is statistically superior in terms of safety. Otherwise, we would interpret the result as either inconclusive or indicative of no added benefit.</p>
<p>We write R code for this analysis as follows that also provides us the power and decision for each interim steps.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>posterior_prob_superiority <span class="ot">&lt;-</span> <span class="cf">function</span>(success_treat, total_treat, success_control, total_control, <span class="at">alpha_prior =</span> <span class="dv">2</span>, <span class="at">beta_prior =</span> <span class="dv">2</span>, <span class="at">n_sim =</span> <span class="dv">5000</span>) {</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  alpha_treat <span class="ot">&lt;-</span> alpha_prior <span class="sc">+</span> success_treat</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  beta_treat  <span class="ot">&lt;-</span> beta_prior <span class="sc">+</span> (total_treat <span class="sc">-</span> success_treat)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  alpha_control <span class="ot">&lt;-</span> alpha_prior <span class="sc">+</span> success_control</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  beta_control  <span class="ot">&lt;-</span> beta_prior <span class="sc">+</span> (total_control <span class="sc">-</span> success_control)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  p_treat_samples <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(n_sim, alpha_treat, beta_treat)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  p_control_samples <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(n_sim, alpha_control, beta_control)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  prob_superior <span class="ot">&lt;-</span> <span class="fu">mean</span>(p_treat_samples <span class="sc">&gt;</span> p_control_samples)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob_superior =</span> prob_superior,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">treat_posterior =</span> <span class="fu">c</span>(<span class="at">alpha =</span> alpha_treat, <span class="at">beta =</span> beta_treat),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">control_posterior =</span> <span class="fu">c</span>(<span class="at">alpha =</span> alpha_control, <span class="at">beta =</span> beta_control),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">samples =</span> <span class="fu">data.frame</span>(<span class="at">p_treat =</span> p_treat_samples, <span class="at">p_control =</span> p_control_samples)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>interims <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">interim1 =</span> <span class="fu">list</span>(<span class="at">treat =</span> <span class="fu">c</span>(<span class="at">success =</span> <span class="dv">17</span>, <span class="at">total =</span> <span class="dv">25</span>), <span class="at">control =</span> <span class="fu">c</span>(<span class="at">success =</span> <span class="dv">15</span>, <span class="at">total =</span> <span class="dv">25</span>)),</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">interim2 =</span> <span class="fu">list</span>(<span class="at">treat =</span> <span class="fu">c</span>(<span class="at">success =</span> <span class="dv">36</span>, <span class="at">total =</span> <span class="dv">50</span>), <span class="at">control =</span> <span class="fu">c</span>(<span class="at">success =</span> <span class="dv">29</span>, <span class="at">total =</span> <span class="dv">50</span>)),</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">interim3 =</span> <span class="fu">list</span>(<span class="at">treat =</span> <span class="fu">c</span>(<span class="at">success =</span> <span class="dv">57</span>, <span class="at">total =</span> <span class="dv">75</span>), <span class="at">control =</span> <span class="fu">c</span>(<span class="at">success =</span> <span class="dv">45</span>, <span class="at">total =</span> <span class="dv">75</span>))</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>efficacy_thresh <span class="ot">&lt;-</span> <span class="fl">0.95</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>futility_thresh <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>final_success_thresh <span class="ot">&lt;-</span> <span class="fl">0.95</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(interims)) {</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> interims[[i]]</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">paste</span>(<span class="st">"Interim: "</span>, i,<span class="st">" -- Sample Size: "</span>, data<span class="sc">$</span>treat[<span class="dv">2</span>],<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>))</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">posterior_prob_superiority</span>(</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">success_treat =</span> data<span class="sc">$</span>treat[<span class="st">"success"</span>],</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_treat =</span> data<span class="sc">$</span>treat[<span class="st">"total"</span>],</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">success_control =</span> data<span class="sc">$</span>control[<span class="st">"success"</span>],</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_control =</span> data<span class="sc">$</span>control[<span class="st">"total"</span>]</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Posterior Pr(treat &gt; control):"</span>, <span class="fu">round</span>(result<span class="sc">$</span>prob_superior, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (result<span class="sc">$</span>prob_superior <span class="sc">&gt;</span> efficacy_thresh) {</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Stop: Evidence for treatment superiority</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">break</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (result<span class="sc">$</span>prob_superior <span class="sc">&lt;</span> (<span class="dv">1</span> <span class="sc">-</span> efficacy_thresh)) {</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Stop: Futility (treatment worse)</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">break</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Continue to next interim</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Interim:  1  -- Sample Size:  25 
Posterior Pr(treat &gt; control): 0.7142 
Continue to next interim
Interim:  2  -- Sample Size:  50 
Posterior Pr(treat &gt; control): 0.925 
Continue to next interim
Interim:  3  -- Sample Size:  75 
Posterior Pr(treat &gt; control): 0.9812 
Stop: Evidence for treatment superiority</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>final_samples <span class="ot">&lt;-</span> result<span class="sc">$</span>samples</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(final_samples, <span class="fu">aes</span>(<span class="at">x =</span> p_treat <span class="sc">-</span> p_control)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Posterior Distribution of Difference: Pr(Treatment) - Pr(Control)"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Difference in Safety Probabilities"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="M06_2_files/figure-html/adaptive_design-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is also possible to do Bayesian power analyses for each intrem steps at the desing stage to identify the sample size required based on the decision rule.</p>
</section>
</section>
<section id="bayesian-model-choice" class="level2">
<h2 class="anchored" data-anchor-id="bayesian-model-choice">Bayesian Model Choice</h2>
<iframe width="500" height="300" src="https://www.youtube.com/embed/VIDEO_ID" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p>Recall that in one of the previous modules, we focused on evaluating the performance of Bayesian models, especially after running Markov Chain Monte Carlo (MCMC) simulations. Where we used, trace plots, R-hat statistic (also called the Gelman-Rubin diagnostic), effective sample size (ESS), autocorrelation checks and posterior predictive checks.</p>
<p>In today’s lecture, we move from model evaluation to model selection, deciding which of several Bayesian models best explains your data, given prior knowledge and model structure. This process is called Bayesian model choice. In this unit, we will mainly discussed few of the methods, such as Bayes Factor and model choice using information criteria.</p>
</section>
<section id="bayes-factor" class="level2">
<h2 class="anchored" data-anchor-id="bayes-factor">Bayes Factor</h2>
<iframe width="500" height="300" src="https://www.youtube.com/embed/VIDEO_ID" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p><span class="citation" data-cites="gelman2013bayesian">Gelman et al. (<a href="references.html#ref-gelman2013bayesian" role="doc-biblioref">2013</a>)</span> page:182</p>
<section id="probabilistic-view-point" class="level3">
<h3 class="anchored" data-anchor-id="probabilistic-view-point">Probabilistic View Point</h3>
<p>The Bayes Factor is a tool used in Bayesian statistics, say to compare two hypotheses. It tells you how much more likely the data is under one hypothesis than another.</p>
<p>Think of it like a ratio:</p>
<p><span class="math display">\[
\text{Bayes Factor (BF)} = \frac{\text{Probability of data if Hypothesis 1 is true}}{\text{Probability of data if Hypothesis 2 is true}}
\]</span></p>
<p>We can write it as:</p>
<p><span class="math display">\[
\text{BF}_{10} = \frac{Pr(\text{Data} \mid H_1)}{Pr(\text{Data} \mid H_0)}
\]</span></p>
<p>where, <span class="math inline">\(H_1\)</span>: Hypothesis one (or alternative hypothesis) e.g., “something is going on” and <span class="math inline">\(H_0\)</span>: Hypothesis two (or null hypothesis ), e.g., “nothing is going on”. Now, if <span class="math inline">\(BF &gt; 1\)</span>, data favors <span class="math inline">\(H_1\)</span> and if <span class="math inline">\(BF &lt; 1\)</span>, data favors <span class="math inline">\(H_0\)</span>.</p>
<p>Let’s go back to the medical practitioner example we have discussed earlier in this unit, where the medical practitioner was trying to determine whether a patient has type-2 diabetes (T2D). Here, now we want to compare two hypotheses:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The patient does not have type-2 diabetes</li>
<li><span class="math inline">\(H_1\)</span>: The patient does have type-2 diabetes</li>
</ul>
<p>The goal is to use the Bayes Factor to compare how likely the observed test result is under each hypothesis.</p>
<p>Let’s assume, the test returns positive if it detects likely diabetes. But, the test is not perfect, it has known sensitivity and specificity.</p>
<p>Let us further assume, the sensitivity (true positive rate) is 90%, i.e., <span class="math inline">\(Pr(\text{Positive test} \mid H_1) = 0.9\)</span>. And the specificity (true negative rate) is 80%, i.e., <span class="math inline">\(Pr(\text{Negative test} \mid H_0) = 0.8\)</span>.</p>
<p>From this, we get:</p>
<p><span class="math display">\[
\begin{aligned}
Pr(\text{Positive test} \mid H_0) &amp;= 1 - 0.8 = 0.2 \\
Pr(\text{Positive test} \mid H_1) &amp;= 0.9
\end{aligned}
\]</span></p>
<p>Hence, we get the Bayes Factor as:</p>
<p><span class="math display">\[
\text{BF}_{10} = \frac{Pr(\text{Positive test} \mid H_1)}{Pr(\text{Positive test} \mid H_0)} = \frac{0.9}{0.2} = 4.5
\]</span> Here, a Bayes Factor of 4.5 means, the observed positive test result is 4.5 times more likely if the patient has type-2 diabetes than if they do not. This is considered a moderate evidence in favor of <span class="math inline">\(H_1\)</span> (i.e., the patient likely has diabetes).</p>
<p>Now, we could combine this with prior belief (say, based on risk factors) using Bayes’ Theorem to get a posterior probability (please see more in the following section), but the Bayes Factor alone tells us how the data shifts the odds between the two hypotheses.</p>
<p>A commonly used guideline for interpreting the Bayes Factor (BF) is as follows::</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bayes Factor <span class="math inline">\(\text{BF}_{10}\)</span></th>
<th>Strength of Evidence for <span class="math inline">\(H_1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 to 3</td>
<td>Weak evidence</td>
</tr>
<tr class="even">
<td>3 to 10</td>
<td>Moderate evidence</td>
</tr>
<tr class="odd">
<td>10 to 30</td>
<td>Strong evidence</td>
</tr>
<tr class="even">
<td>&gt; 100</td>
<td>Decisive evidence</td>
</tr>
</tbody>
</table>
<p>Note that we can also define Bayes Factor (BF) changing the hypothesis that we are interested, i.e., if we write <span class="math inline">\(BF_{01}\)</span> instead of <span class="math inline">\(BF_{10}\)</span>, then we are interested in <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Compared to Frequentist p-values</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 41%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Bayes Factor</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Compares hypotheses?</td>
<td>Yes (directly compares <span class="math inline">\(H_1\)</span> and <span class="math inline">\(H_0\)</span>)</td>
<td>No (tests <span class="math inline">\(H_0\)</span> only)</td>
</tr>
<tr class="even">
<td>Probability statement?</td>
<td>Yes (about models)</td>
<td>No (about data given <span class="math inline">\(H_0\)</span>)</td>
</tr>
<tr class="odd">
<td>Depends on prior?</td>
<td>Yes</td>
<td>No</td>
</tr>
</tbody>
</table>
</section>
<section id="bf-for-bayesian-models" class="level3">
<h3 class="anchored" data-anchor-id="bf-for-bayesian-models">BF for Bayesian Models</h3>
<p>Now let us discuss how we can use this concept of Bayes Factor in Bayesian model selection. Here, Bayes factor is the ratio of two marginal likelihoods obtained from the two models.</p>
<p>In Bayesian statistics, model selection is based on the posterior probabilities of models, given the observed data. Suppose we have two competing models, <span class="math inline">\(\mathcal{M}_1\)</span> and <span class="math inline">\(\mathcal{M}_2\)</span>. Given observed data <span class="math inline">\(D\)</span>, the Bayesian approach computes the posterior probability of each model using Bayes’ theorem:</p>
<p><span class="math display">\[
p(\mathcal{M}_i \mid D) = \frac{p(D \mid \mathcal{M}_i) p(\mathcal{M}_i)}{p(D)}; \quad i \in \{1,2\}
\]</span></p>
<p>Here, <span class="math inline">\(p(D \mid \mathcal{M}_i)\)</span> is the marginal likelihood or evidence for model <span class="math inline">\(\mathcal{M}_i\)</span>, <span class="math inline">\(p(\mathcal{M}_i)\)</span> is the prior probability of model <span class="math inline">\(\mathcal{M}_i\)</span> and <span class="math inline">\(p(D)\)</span> is the marginal probability of the data across all models.</p>
<p>The marginal likelihood is computed by integrating the likelihood over the model’s parameter space:</p>
<p><span class="math display">\[
p(D \mid \mathcal{M}_i) = \int p(D \mid \theta_i, \mathcal{M}_i) p(\theta_i \mid \mathcal{M}_i) \, d\theta_i \quad i \in \{1,2\}
\]</span></p>
<p>This marginal likelihood balances model fit (via the likelihood) with model complexity (via the prior).</p>
<p>Now, as we have mentioned earlier, the Bayes Factor is the ratio of the marginal likelihoods of these two models:</p>
<p><span class="math display">\[
\text{BF}_{12} = \frac{p(D \mid \mathcal{M}_1)}{p(D \mid \mathcal{M}_2)}
\]</span></p>
<ul>
<li><span class="math inline">\(\text{BF}_{12} &gt; 1\)</span>: Evidence favors model <span class="math inline">\(\mathcal{M}_1\)</span></li>
<li><span class="math inline">\(\text{BF}_{12} &lt; 1\)</span>: Evidence favors model <span class="math inline">\(\mathcal{M}_2\)</span></li>
<li><span class="math inline">\(\text{BF}_{12} = 1\)</span>: Both models are equally supported by the data</li>
</ul>
<p>This ratio quantifies how much more likely the data is under one model than another, independent of prior beliefs about the models.</p>
<p>If we include model priors, the posterior odds in favor of <span class="math inline">\(\mathcal{M}_1\)</span> over <span class="math inline">\(\mathcal{M}_2\)</span> become:</p>
<p><span class="math display">\[
\begin{aligned}
\frac{p(\mathcal{M}_1 \mid D)}{p(\mathcal{M}_2 \mid D)} &amp;= \text{BF}_{12} \cdot \frac{p(\mathcal{M}_1)}{p(\mathcal{M}_2)} \\
\implies \text{BF}_{12} &amp;= \frac{p(\mathcal{M}_1 \mid D)}{p(\mathcal{M}_2 \mid D)}\cdot \frac{p(\mathcal{M}_2)}{p(\mathcal{M}_1)}
\end{aligned}
\]</span></p>
<p>Thus, Bayes Factor serves as the updating factor for the prior odds between two models, given the prior distributions of the models <span class="math inline">\(p(\mathcal{M}_i)\)</span>, <span class="math inline">\(i\in \{1,2\}\)</span>.</p>
</section>
<section id="example-in-practice" class="level3">
<h3 class="anchored" data-anchor-id="example-in-practice">Example in Practice</h3>
<p>Let us recall the C-reactive protein (CRP) data example we discussed earlier in this unit. In that example, we used a Bayesian hierarchical model with age, sex, and antibiotic status as predictor variables. Now, we might want to investigate whether adding more variables to the model improves the results. For instance, we may consider including the sepsis and discharge status variables. The idea is to fit two models, one without sepsis and discharge variables (say <code>crp_model1</code>), and another with them (say <code>crp_model2</code>), and then use the Bayes factor to compare the models.</p>
<p>We write R for this as follows:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>crp_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"crp_data_complete.csv"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>crp_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ID =</span> crp_data<span class="sc">$</span>ID,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">CRP =</span> crp_data<span class="sc">$</span>crp,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">CRP_log =</span> <span class="fu">log</span>(crp_data<span class="sc">$</span>crp),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Day =</span> crp_data<span class="sc">$</span>day,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Antibiotic =</span> <span class="fu">as.factor</span>(crp_data<span class="sc">$</span>antib_1h),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Age =</span> crp_data<span class="sc">$</span>age,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sex =</span> <span class="fu">as.factor</span>(crp_data<span class="sc">$</span>SEX),</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sepsis =</span> <span class="fu">as.factor</span>(crp_data<span class="sc">$</span>SEPSIS),</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Discharge =</span> <span class="fu">as.factor</span>(crp_data<span class="sc">$</span>discharge_r)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>priors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">class =</span> <span class="st">"Intercept"</span>), <span class="co"># prior for global intercept</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">class =</span> <span class="st">"b"</span>), <span class="co"># prior for all fixed effects</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">cauchy</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">class =</span> <span class="st">"sd"</span>), <span class="co"># prior for random intercept SD</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">cauchy</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">class =</span> <span class="st">"sigma"</span>) <span class="co"># prior for residual SD</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>crp_model1 <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> CRP_log <span class="sc">~</span> Day <span class="sc">+</span> Age <span class="sc">+</span> Sex <span class="sc">+</span> Antibiotic <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> ID),</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> crp_data,</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior =</span> priors,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">2</span>,</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">cores =</span> <span class="dv">2</span>,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">iter =</span> <span class="dv">2000</span>,</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">warmup =</span> <span class="dv">1000</span>,</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">1234</span>,</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.95</span>),</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">save_all_pars =</span> <span class="cn">TRUE</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>crp_model2 <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> CRP_log <span class="sc">~</span> Day <span class="sc">+</span> Age <span class="sc">+</span> Sex <span class="sc">+</span> Antibiotic <span class="sc">+</span> Sepsis <span class="sc">+</span> Discharge <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> ID),</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> crp_data,</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior =</span> priors,</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">2</span>,</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">cores =</span> <span class="dv">2</span>,</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">iter =</span> <span class="dv">2000</span>,</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">warmup =</span> <span class="dv">1000</span>,</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">1234</span>,</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.95</span>),</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">save_pars =</span> <span class="fu">save_pars</span>(<span class="at">all=</span><span class="cn">TRUE</span>)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a><span class="co"># compute Bayes factors </span></span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a><span class="fu">bayes_factor</span>(crp_model2, crp_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Bayes factor in favor of crp_model2 over crp_model1: 4.36971</code></pre>
</div>
</div>
<p>The result shows that the CRP model with sepsis and discharge variables (i.e., <code>crp_model2</code>) provide more insight compared to the model without these variables (i.e., <code>crp_model1</code>).</p>
<p>Now, we can also get the posterior model probabilities from marginal likelihoods. If you compare multiple Bayesian models using Bayes factors, you can use them to compute posterior model probabilities, i.e., the probability that each model is true, given the observed data.</p>
<p>For these two models <code>crp_model2</code> and <code>crp_model1</code>, we compute the Bayes Factor:</p>
<p><span class="math display">\[
\text{BF}_{21} = \text{BF}_{\text{model2},\text{model1}}= \frac{p(\text{data} \mid \text{model2})}{p(\text{data} \mid \text{model1})} = 3.5
\]</span></p>
<p>Then, assuming equal prior model probabilities, i.e., <span class="math inline">\(p(\text{model2}) = p(\text{model1}) = 0.5\)</span>, we get the posterior probability of each model:</p>
<p><span class="math display">\[
p(\text{model2} \mid \text{data}) = \frac{\text{BF}_{21} \cdot p(\text{model2})}{\text{BF}_{21} \cdot p(\text{model2}) + p(\text{model1})}
\]</span></p>
<p>Which simplifies (with equal priors) to:</p>
<p><span class="math display">\[
\begin{aligned}
p(\text{model2} \mid \text{data}) &amp;= \frac{BF_{21}}{BF_{21} + 1}\\
p(\text{model1} \mid \text{data}) &amp;= \frac{1}{BF_{21} + 1}
\end{aligned}
\]</span></p>
<p>There asre the posterior model probabilities for each models from their marginal likelihoods. Hence, we can get the marginal posterior probabilities as:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the posterior model probabilities from Marginal Likelihoods</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">post_prob</span>(crp_model2, crp_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>crp_model2 crp_model1 
 0.8137703  0.1862297 </code></pre>
</div>
</div>
<p>Now, suppose the prior model probabilities are not same, i.e., <span class="math inline">\(p(\text{model2}) = 0.25\)</span> and <span class="math inline">\(p(\text{model1}) = 0.75\)</span>, then we get the marginal posterior probabilities as:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specify prior model probabilities</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">post_prob</span>(crp_model2, crp_model1, <span class="at">prior_prob =</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>crp_model2 crp_model1 
 0.3268367  0.6731633 </code></pre>
</div>
</div>
<p>We can see from the results that how the prior preference for models can lead to a shift in the marginal posterior probabilities for the models and hence the selection choice.</p>
</section>
</section>
<section id="information-criteria" class="level2">
<h2 class="anchored" data-anchor-id="information-criteria">Information Criteria</h2>
<iframe width="500" height="300" src="https://www.youtube.com/embed/VIDEO_ID" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p>In Bayesian statistics, information criteria are also used to compare models. Some common information criteria include the Deviance Information Criterion (DIC), the Watanabe–Akaike Information Criterion or also known as the Widely Applicable Information Criterion (WAIC), and Leave-One-Out Cross-Validation (LOO). Below, we provide the details of these criteria.</p>
<section id="dic" class="level3">
<h3 class="anchored" data-anchor-id="dic">DIC</h3>
<p>The Deviance Information Criterion (DIC) is particularly useful when we’re working with models estimated via Markov Chain Monte Carlo (MCMC) methods. It balances model fit and complexity, giving us a way to choose between competing Bayesian models. Like AIC (Akaike Information Criterion) in the frequentist setting, DIC aims to prevent overfitting by penalising models that are too complex.</p>
<p>To calculate DIC, we first compute the deviance, which is defined as <span class="math inline">\(D(\theta) = -2 \log p(y \mid \theta)\)</span>, where <span class="math inline">\(y\)</span> is the observed data and <span class="math inline">\(\theta\)</span> represents the model parameters. We then take the posterior mean of the deviance (denoted <span class="math inline">\(\overline{D(\theta)}\)</span>) across MCMC samples. The DIC itself is given by the formula:</p>
<p><span class="math display">\[
\text{DIC} = \overline{D(\theta)} + p_D
\]</span></p>
<p>Here, <span class="math inline">\(p_D = \overline{D(\theta)} - D(\overline{\theta})\)</span> is the effective number of parameters, which serves as a complexity penalty. <span class="math inline">\(D(\overline{\theta})\)</span> is the deviance evaluated at the posterior mean of the parameters. A lower DIC indicates a better trade-off between model fit and complexity, so we generally prefer models with lower DIC values.</p>
<p>There are several advantages to using DIC. First, it’s relatively easy to compute from MCMC output, making it convenient when we’re already using Bayesian estimation methods. DIC also provides a straightforward way to assess the fit of models that are not nested, and it helps account for overfitting by penalizing model complexity through the effective number of parameters.</p>
<p>However, DIC also has limitations. It may not perform well for hierarchical or latent variable models, especially when the posterior distributions are highly skewed or multimodal. Since DIC relies on the posterior mean of the parameters, it can give misleading results if that mean doesn’t accurately reflect the shape of the full posterior distribution. In such cases, it might underestimate the model complexity or produce overly optimistic estimates of model fit.</p>
<p>Because of these issues, we might consider using more robust alternatives like WAIC or LOO-CV , especially when dealing with more complex models. Nevertheless, DIC remains a useful and accessible tool for many Bayesian model comparison tasks, particularly when the models and posteriors are relatively simple and well-behaved.</p>
</section>
<section id="waic" class="level3">
<h3 class="anchored" data-anchor-id="waic">WAIC</h3>
<p>When comparing Bayesian models, we often look for a criterion that not only rewards good fit but also guards against overfitting. The WAIC serves this purpose and is considered an improvement over earlier methods like the DIC, especially for complex or hierarchical models. Unlike DIC, which relies on point estimates, WAIC fully integrates over the posterior distribution, making it more aligned with the Bayesian philosophy.</p>
<p>To compute WAIC, we begin by evaluating the log-likelihood of each individual data point at every iteration of our MCMC samples. This allows us to measure how well the model predicts the data, on average, across the posterior. The sum of these log-likelihoods, averaged across samples, gives us the log pointwise predictive density (lppd). To adjust for model complexity, we estimate the effective number of parameters, <span class="math inline">\(p_{\text{WAIC}}\)</span>, based on how much the log-likelihood varies across the samples. The WAIC formula is:</p>
<p><span class="math display">\[
\text{WAIC} = -2 \left( \text{lppd} - p_{\text{WAIC}} \right)
\]</span></p>
<p>In practice, WAIC allows us to assess how well a model would perform on new, unseen data. The smaller the WAIC value, the better the model’s predictive performance. One of the key strengths of WAIC is that it operates on a pointwise level, meaning it evaluates model fit for each observation independently. This makes it more flexible and reliable, especially when we are working with models that include latent variables, non-linear structures, or non-i.i.d. observations.</p>
<p>While WAIC offers many advantages, it is not without limitations. It requires us to retain and process the full array of log-likelihood values from our MCMC samples, which can be computationally demanding for large datasets. Additionally, the reliability of WAIC depends heavily on the convergence and quality of the posterior samples. Poor MCMC mixing or insufficient sampling can result in inaccurate estimates of model performance.</p>
<p>Still, WAIC is one of the most general-purpose and robust information criteria available for Bayesian model comparison. It provides a principled way to choose among models based on their predictive accuracy, rather than just fit alone, and is especially useful when our models go beyond simple parametric forms.</p>
</section>
<section id="loo" class="level3">
<h3 class="anchored" data-anchor-id="loo">LOO</h3>
<p>When we want to evaluate how well a Bayesian model predicts new data, Leave-One-Out (LOO) Cross-Validation provides one of the most intuitive and accurate approaches. In essence, LOO estimates the model’s predictive performance by systematically leaving out each observation in the dataset, fitting the model to the remaining data, and then measuring how well it predicts the left-out point. This process is repeated for every data point, giving us a robust estimate of out-of-sample predictive accuracy.</p>
<p>In Bayesian settings, we rarely re-fit the model <span class="math inline">\(n\)</span> times for <span class="math inline">\(n\)</span> observations because it would be too computationally expensive. Instead, we use methods like Pareto-smoothed importance sampling (PSIS-LOO), which approximate LOO using existing MCMC samples. This makes LOO practical while still maintaining high accuracy in most cases.</p>
<p>The result of LOO is typically expressed as:</p>
<p><span class="math display">\[
\text{LOO} = -2 \sum_{i=1}^n \log p(y_i \mid y_{-i})
\]</span></p>
<p>Here, <span class="math inline">\(p(y_i \mid y_{-i})\)</span> is the posterior predictive density for observation <span class="math inline">\(i\)</span>, given all other data points. A lower LOO score indicates better predictive performance. Since LOO directly evaluates generalization to unseen data, it is often considered the gold standard for model comparison in Bayesian analysis.</p>
<p>LOO has several key strengths. First, it is fully Bayesian and does not rely on point estimates or asymptotic approximations. It is also more robust than DIC and, in some cases, WAIC, particularly when the model is complex or the likelihood is sensitive to small changes in the data. Moreover, LOO provides diagnostic tools that help us detect when certain data points are too influential or when the approximation might be unreliable.</p>
<p>However, LOO is not without its drawbacks. While PSIS-LOO makes the method computationally feasible, it still relies on the assumption that importance sampling provides a good approximation. If the approximation breaks down, often due to high variance in the importance weights, LOO estimates can become unstable. In such cases, we might need to fall back on exact cross-validation or reconsider the model specification.</p>
<p>Overall, we find that LOO offers one of the most reliable and interpretable assessments of predictive performance for Bayesian models. It directly measures how well our model generalizes, which is usually the main goal in statistical modeling. When used alongside WAIC or as a standalone metric, LOO helps us make informed decisions about which model is likely to perform best on future data.</p>
</section>
<section id="example-in-practice-1" class="level3">
<h3 class="anchored" data-anchor-id="example-in-practice-1">Example in Practice</h3>
<p>Now we implement these information criteria to select the best Bayesian model related to the C-reactive protein models discussed earlier. The <code>crp_model2</code> includes all predictor variables (i.e., age, sex, antibiotic use, sepsis, and discharge), while <code>crp_model1</code> excludes the sepsis and discharge variables.</p>
<p><strong>DIC</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(loo)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>dic_brm <span class="ot">&lt;-</span> <span class="cf">function</span>(fit){</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>   log_lik_matrix <span class="ot">&lt;-</span> <span class="fu">log_lik</span>(fit)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>   deviance_pointwise <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> log_lik_matrix</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>   D_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">rowSums</span>(deviance_pointwise))</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>   posterior_mean <span class="ot">&lt;-</span> <span class="fu">posterior_summary</span>(fit)[, <span class="st">"Estimate"</span>]</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>   D_hat <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(<span class="fu">colMeans</span>(<span class="fu">exp</span>(log_lik_matrix))))</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>   p_D <span class="ot">&lt;-</span> D_bar <span class="sc">-</span> D_hat</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>   DIC <span class="ot">&lt;-</span> D_bar <span class="sc">+</span> p_D</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>   df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">DIC=</span>DIC, <span class="at">D_bar=</span>D_bar, <span class="at">p_D=</span>p_D)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">row.names</span>(df) <span class="ot">&lt;-</span> <span class="st">"Estimate"</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>   <span class="fu">return</span>(df)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"CRP Model 1: "</span>); <span class="fu">dic_brm</span>(crp_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRP Model 1: "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>              DIC    D_bar      p_D
Estimate 757.9466 703.6482 54.29845</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"CRP Model 2: "</span>); <span class="fu">dic_brm</span>(crp_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRP Model 2: "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             DIC    D_bar      p_D
Estimate 755.808 702.7549 53.05307</code></pre>
</div>
</div>
<p>The output provides a comparison between two Bayesian hierarchical models, CRP Model 1 and CRP Model 2, using the DIC. As we have already discussed, a lower DIC value indicates a better model, assuming all else is equal.</p>
<p>Looking at the results, model 1 has a DIC of 757.95, a posterior mean deviance <span class="math inline">\((\bar{D})\)</span> of 703.65, and an effective number of parameters <span class="math inline">\((p_D)\)</span> of 54.30. In comparison, model 2 has a slightly lower DIC of 755.81, a <span class="math inline">\(\bar{D}\)</span> of 702.75, and a <span class="math inline">\(p_D\)</span> of 53.05. These values suggest that model 2 fits the data slightly better (as shown by the lower <span class="math inline">\(\bar{D}\)</span>) and is marginally less complex (as shown by the lower <span class="math inline">\(p_D\)</span>).</p>
<p>Overall, while the difference in DIC between the two models is relatively small, approximately 2.14 points, the CRP Model 2 performs marginally better in terms of both model fit and simplicity. Although a DIC difference greater than 5 to 10 is typically considered more substantial, the results still suggest that CRP Model 2 is the preferred model in this comparison.</p>
<p><strong>WAIC</strong></p>
<p>Now for the same Bayesian hierarchical models, we calculate the WAIC as follows:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(loo)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>waic1 <span class="ot">&lt;-</span> <span class="fu">waic</span>(crp_model1)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>waic2 <span class="ot">&lt;-</span> <span class="fu">waic</span>(crp_model2)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"CRP Model 1: "</span>); waic1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRP Model 1: "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Computed from 2000 by 432 log-likelihood matrix.

          Estimate   SE
elpd_waic   -387.1 17.7
p_waic        62.5  4.8
waic         774.3 35.5

34 (7.9%) p_waic estimates greater than 0.4. We recommend trying loo instead. </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"CRP Model 2: "</span>); waic2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRP Model 2: "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Computed from 2000 by 432 log-likelihood matrix.

          Estimate   SE
elpd_waic   -385.7 17.8
p_waic        60.9  4.8
waic         771.5 35.6

34 (7.9%) p_waic estimates greater than 0.4. We recommend trying loo instead. </code></pre>
</div>
</div>
<p>The output presents WAIC results, and as we know like DIC, lower WAIC values generally indicate better model performance. We can see the WAIC for model 2 is smaller compared to the model 1.</p>
<p>Both models were evaluated using a log-likelihood matrix with 2000 posterior samples across 432 observations. A key diagnostic mentioned in the output is that 34 (7.9%) of the p_waic estimates (pointwise effective number of parameters) are greater than 0.4 for each model.</p>
<p>This suggests some instability or potential problems with the WAIC approximation for these Bayesian hierarchical models. When a noticeable proportion of p_waic values are this high, it indicates that the model may not be well-behaved in some data regions. As a result, the tool recommends using LOO (Leave-One-Out cross-validation) instead, which is often more robust.</p>
<p>Now we can also use the function <code>loo_compare()</code>, which gives difference in expected log predictive density (elpd). In this case, as we have use WAIC, hence use of <code>loo_compare()</code> function will provide difference in elpd_waic values. We can see that model 2 has an elpd_diff (of WAIC) of 0.0, while model 1 has an elpd_diff (of WAIC) of -1.4 with a standard error of 1.8. This means CRP model 2 performs slightly better in terms of predictive accuracy, but the difference is not statistically significant, since the difference is small and well within the range of uncertainty. In practical terms, we can say, both models perform similarly, and the choice might come down to factors like interpretability or theoretical justification.</p>
<p><strong>LOO</strong></p>
<p>Now, we get the results using LOO as:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(loo)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>loo1 <span class="ot">&lt;-</span> <span class="fu">loo</span>(crp_model1, <span class="at">moment_match =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>loo2 <span class="ot">&lt;-</span> <span class="fu">loo</span>(crp_model2, <span class="at">moment_match =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"CRP Model 1: "</span>); loo1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRP Model 1: "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Computed from 2000 by 432 log-likelihood matrix.

         Estimate   SE
elpd_loo   -388.5 17.9
p_loo        63.9  4.9
looic       777.1 35.8
------
MCSE of elpd_loo is 0.2.
MCSE and ESS estimates assume MCMC draws (r_eff in [0.3, 2.7]).

All Pareto k estimates are good (k &lt; 0.7).
See help('pareto-k-diagnostic') for details.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"CRP Model 2: "</span>); loo2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRP Model 2: "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Computed from 2000 by 432 log-likelihood matrix.

         Estimate   SE
elpd_loo   -386.8 17.9
p_loo        61.9  4.8
looic       773.6 35.7
------
MCSE of elpd_loo is 0.2.
MCSE and ESS estimates assume MCMC draws (r_eff in [0.4, 2.1]).

All Pareto k estimates are good (k &lt; 0.7).
See help('pareto-k-diagnostic') for details.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">loo_compare</span>(loo1, loo2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           elpd_diff se_diff
crp_model2  0.0       0.0   
crp_model1 -1.7       1.8   </code></pre>
</div>
</div>
<p>The output presents a comparison between CRP model 1 and model 2 with LOO, and we already know LOO is a robust method for estimating out-of-sample predictive accuracy in Bayesian models. This method evaluates how well a model is expected to predict new data by systematically leaving out each observation and computing the model’s performance.</p>
<p>For model 1, the estimated expected log predictive density (elpd_loo) is -388.5, with a standard error of 17.9. The effective number of parameters (p_loo) is 63.9, and the LOO Information Criterion (looic), which is simply <code>-2 * elpd_loo</code> is 777.1. All diagnostic values, including Pareto k estimates, are in the safe range (all k &lt; 0.7), which indicates reliable LOO estimates. The Monte Carlo standard error (MCSE) for <code>elpd_loo</code> is just 0.2, suggesting stable estimation.</p>
<p>For model 2, the elpd_loo is -386.8, with the same standard error of 17.9, a slightly lower p_loo of 61.9, and a looic of 773.6. Like model 1, all diagnostic measures are within acceptable bounds, and the MCSE of elpd_loo is also 0.2, indicating reliable MCMC sampling.</p>
<p>The <code>loo_compare()</code> output shows that model 2 has a slightly better elpd_loo than model 1, with a difference (elpd_diff) of 1.7 in favor of model 2. However, the standard error of this difference is 1.8, meaning that the difference is not statistically significant, it’s well within the margin of uncertainty. This suggests that, while model 2 is marginally preferred, both models perform nearly identically.</p>
<!--

## Bayesian Shrinkage


### Regularising Prior (stronger shrinkage)

* **Prior**: $\beta_1 \sim \mathcal{N}(0, 1^2)$
* **Interpretation**: You assume most effects are small or near zero. Useful in high-dimensional or noisy settings.
* **Why use it?**: Helps with model stability, especially with correlated predictors.


### Horseshoe Prior (for sparse signals)

* Particularly helpful if you think most predictors have near-zero effect but a few may be strong.
* **Prior**: $\beta_1 \sim \text{Horseshoe}(0, \tau)$
* **Interpretation**: Shrinks small effects to zero, but allows strong signals to remain.
* **Use case**: More common in high-dimensional models, but can still be useful if model includes many covariates.

## Bayesian Prediction


<iframe width="500" height="300" src="https://www.youtube.com/embed/VIDEO_ID" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

Bayesian prediction is the process of forecasting future or unseen data by integrating over the uncertainty in model parameters using the posterior distribution. Unlike classical prediction (which often plugs in point estimates of parameters), Bayesian prediction integrates over the entire posterior distribution of the model parameters. This means predictions are not just a single value but a distribution that reflects both uncertainty in the data (randomness, noise) and uncertainty in the model parameters (posterior uncertainty)

Suppose you’ve observed data $D$, and you're interested in predicting a new observation $\tilde{y}$, possibly at a new covariate $\tilde{x}$.

Recall that in Bayesian inference, the posterior predictive distribution is:

$$
p(\tilde{y} \mid D) = \int p(\tilde{y} \mid \theta) \, p(\theta \mid D) \, d\theta
$$

* $p(\tilde{y} \mid \theta)$: likelihood of new data given parameters
* $p(\theta \mid D)$: posterior distribution of parameters
* $p(\tilde{y} \mid D)$: posterior predictive distribution

So you integrate over the posterior to get predictions, not just plug in a point estimate.


Imagine a Bayesian linear regression:

$$
y_i \sim N(\beta_0 + \beta_1 x_i, \sigma^2)
$$

After fitting the model, the Bayesian prediction for a new $x^*$ is **not just** $\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x^*$, but rather a distribution over possible $y^*$, incorporating the full posterior over $\beta_0$, $\beta_1$, and $\sigma$.



-->
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
</section>
<section id="live-tutorial-and-discussion" class="level2">
<h2 class="anchored" data-anchor-id="live-tutorial-and-discussion">Live tutorial and discussion</h2>
<p>The final learning activity for this week is the live tutorial and discussion. This tutorial is an opportunity for you to to interact with your teachers, ask questions about the course, and learn about biostatistics in practice. You are expected to attend these tutorials when possible for you to do so. For those that cannot attend, the tutorial will be recorded and made available on Canvas. We hope to see you there!</p>
</section>
<section id="tutorial-exercises" class="level2">
<h2 class="anchored" data-anchor-id="tutorial-exercises">Tutorial Exercises</h2>
<p>Solutions will be provided later after the tutorial.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-berry2010bayesian" class="csl-entry" role="listitem">
Berry, Scott M, Bradley P Carlin, J Jack Lee, and Peter Muller. 2010. <em>Bayesian Adaptive Methods for Clinical Trials</em>. CRC press.
</div>
<div id="ref-gelman2013bayesian" class="csl-entry" role="listitem">
Gelman, Andrew, John B Carlin, Hal S Stern, David B Dunson, Aki Vehtari, and Donald B Rubin. 2013. <em>Bayesian Data Analysis (3rd Edition)</em>. Chapman; Hall/CRC.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./M06_1.html" class="pagination-link" aria-label="Week 11: **Size Matters!**">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Week 11: <strong>Size Matters!</strong></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>